name: schatzsuche
version: '1.0'
main: de.youtuberinsel.schnitzeljagdtipps.Schnitzeljagdtipps
api-version: '1.20'

commands:
  schatzsuche:
    description: Startet eine Schatzsuche
  schatzsuche_setup:
    description: erlaubt eintr채ge zu ver채ndern
  schatzsuche_progress:
    description: erlaubt die schatzsuche weiterzuf체hren
  tipp:
    description: Gibt tipps f체r die Schatzsuche

permissions:
  youtuberinsel.schatzsuche.start:
    description: erlaubt an einer schatzsuche teilzunehmen
    default: op
  youtuberinsel.schatzsuche.setup:
    description: erlaubt die schatzsuche zu editieren
    default: op
  youtuberinsel.schatzsuche.progress:
    description: erlaubt einen spieler in der schatzsuche voranzubringen
    default: op
